<?php
/**
 * Created by PhpStorm.
 * User: asus
 * Date: 2017/11/9
 * Time: 10:56
 */

namespace backend\models;


use yii\base\Model;

class AdminForm extends Model
{
    public $adminName;
    public $password;
    public $rememberMe;
    public function rules()
    {
        return [
            [['adminName','password'],'required'],
            [['rememberMe'],'safe']
        ]; // TODO: Change the autogenerated stub
    }

    public function attributeLabels()
    {
        return[
          'adminName'=>'用户名',
          'password'=>'登录密码',
         'rememberMe'=>'自动登录',
        ]; // TODO: Change the autogenerated stub
    }
}